name: Deploy-main

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: slack-view
      dockerfile: Dockerfile
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
